### PR TITLE
[BotW] Added an option for bloom intensity

### PR DESCRIPTION
**Pull request by Ryce-Fast**
I added an option for bloom intensity in-game and in inventory.

0%
Screenshot_2024-05-09_16-47-29
Screenshot_2024-05-09_16-47-25

200%
Screenshot_2024-05-10_13-34-06
Screenshot_2024-05-09_17-28-44
Screenshot_2024-05-10_13-33-23

### CODE REVIEW

**Comment by Crementif** [comment]
Nice work! How does this compare to Clarity's existing bloom option? The clarity shader can change the bloom on a percentage basis which I prefer over this on/off version that uses graphic pack rules.

**Comment by Ryce-Fast** [comment]
> Nice work! How does this compare to Clarity's existing bloom option? The clarity shader can change the bloom on a percentage basis which I prefer over this on/off version that uses graphic pack rules.

Are you saying I need to edit in the clarity file?

**Comment by Crementif** [comment]
Yeah, you can change the bloom in the Clarity shader too. See this file: https://github.com/cemu-project/cemu_graphic_packs/blob/master/src/BreathOfTheWild/Enhancements/37040a485a29d54e_00000000000003c9_ps.txt.

**Comment by Ryce-Fast** [comment]
I finally decided to increase the intensity of the bloom

**Comment by Ryce-Fast** [comment]
I removed 250% and 300% because it's too high. 200% is very good !

**Comment by Ryce-Fast** [comment]
@Crementif Ready for review or changes!

**Pull request closed without merging**
